import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { promises as fs, readFileSync } from "node:fs";
import builtins from "builtin-modules";

const prod = process.argv[2] === "production";
const vaultMode = process.argv.includes("--vault");
const vaultDir = process.env.OBSIDIAN_VAULT_DIR?.trim() || readLocalVaultDir();
const artifactFiles = ["main.js", "manifest.json", "styles.css"];

/** Read the local Vault path without requiring it to be committed to the repo. */
function readLocalVaultDir() {
	try {
		const content = readFileSync(path.resolve(".env"), "utf8");
		const line = content
			.split(/\r?\n/)
			.find((entry) => entry.trim().startsWith("OBSIDIAN_VAULT_DIR="));
		if (!line) return "";

		const value = line.slice("OBSIDIAN_VAULT_DIR=".length).trim();
		return value.replace(/^([\"'])(.*)\1$/, "$2").trim();
	} catch {
		return "";
	}
}

if (vaultMode && !vaultDir) {
	throw new Error("未配置 Vault 路径，请设置 OBSIDIAN_VAULT_DIR 或填写项目根目录 .env。");
}

/** Read the plugin ID so local output always follows manifest.json. */
async function readPluginId() {
	const manifestPath = path.resolve("manifest.json");
	const content = await fs.readFile(manifestPath, "utf8");
	const manifest = JSON.parse(content);
	const pluginId = typeof manifest.id === "string" ? manifest.id.trim() : "";

	if (!pluginId) {
		throw new Error("manifest.json 缺少有效的 id 字段，无法同步到 Vault。");
	}

	return pluginId;
}

/** Copy complete plugin artifacts into the local Vault after a successful build. */
async function syncArtifactsToVault() {
	if (!vaultMode) return;

	const pluginId = await readPluginId();
	const pluginDir = path.join(vaultDir, ".obsidian", "plugins", pluginId);
	const currentStat = await fs.lstat(pluginDir).catch(() => null);

	if (currentStat?.isSymbolicLink()) {
		await fs.rm(pluginDir, { recursive: true, force: true });
	}

	await fs.mkdir(pluginDir, { recursive: true });

	for (const fileName of artifactFiles) {
		const sourcePath = path.resolve(fileName);
		const targetPath = path.join(pluginDir, fileName);
		await fs.access(sourcePath).catch(() => {
			throw new Error(`未找到必需产物 ${fileName}，请先完成构建。`);
		});

		const tempPath = `${targetPath}.tmp-${Date.now()}`;
		await fs.copyFile(sourcePath, tempPath);
		await fs.rename(tempPath, targetPath);
	}

	console.log(`[vault-sync] 已同步到 ${pluginDir}`);
}

const vaultSyncPlugin = {
	name: "vault-sync-plugin",
	setup(build) {
		build.onEnd(async (result) => {
			if (!vaultMode || result.errors.length > 0) return;

			try {
				await syncArtifactsToVault();
			} catch (error) {
				process.exitCode = 1;
				console.error(
					`[vault-sync] 同步失败: ${error instanceof Error ? error.message : String(error)}`,
				);
			}
		});
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [vaultSyncPlugin],
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
